# This is a basic workflow to help you get started with Actions

name: guest_token

# Controls when the workflow will run
on:
  # schedule:
  #   - cron: '*/60  * * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Init codes
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
              python-version: 3.9
      - name: Prepare for python Environment
        run: |
            cd guest
            pip install -r requirements.txt
      - name: Prepare for PhantoJS
        run: |
            cd guest
            tar -xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            cp ./phantomjs-2.1.1-linux-x86_64/bin/phantomjs ./
            rm -r phantomjs-2.1.1-linux-x86_64
      - name: Run
        run: |
            cd guest
            python auto_token.py
            rm phantomjs
            rm ghostdriver.log
      - name: commit
        run: |
            git config --global user.email 9173011623@njau.edu.cn
            git config --global user.name kanomahoro
            git add .
            git commit -m "update" -a
            
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
            
  
